"""Using flask-moment to generate displayed timezones rather than user config

Revision ID: 10303703c93e
Revises: 276778ea5914
Create Date: 2024-11-12 14:29:51.189919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10303703c93e'
down_revision = '276778ea5914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_tz')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_tz', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
