"""Reset after sqlite migrations had issues with MySQL Docker image

Revision ID: 276778ea5914
Revises: 
Create Date: 2024-11-12 13:04:22.405925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276778ea5914'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('pref_language', sa.String(length=5), nullable=True),
    sa.Column('user_tz', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('companion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_user_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=64), server_default='Other', nullable=False),
    sa.Column('realism', sa.String(length=64), server_default='Realistic', nullable=False),
    sa.Column('companion_name', sa.String(length=64), nullable=False),
    sa.Column('created_at_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['associated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companion_associated_user_id'), ['associated_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companion_created_at_ts'), ['created_at_ts'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companion_created_at_ts'))
        batch_op.drop_index(batch_op.f('ix_companion_associated_user_id'))

    op.drop_table('companion')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
