"""companions table

Revision ID: 28a6e96f903e
Revises: 1dbb99d9729b
Create Date: 2024-06-10 15:45:05.558720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a6e96f903e'
down_revision = '1dbb99d9729b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_user_id', sa.Integer(), nullable=False),
    sa.Column('companion_name', sa.String(length=64), nullable=False),
    sa.Column('created_at_ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['associated_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companion_associated_user_id'), ['associated_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companion_created_at_ts'), ['created_at_ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companion_created_at_ts'))
        batch_op.drop_index(batch_op.f('ix_companion_associated_user_id'))

    op.drop_table('companion')
    # ### end Alembic commands ###
