"""Adding new cols & default vals

Revision ID: 4d7359f1d51d
Revises: 54a43c606b0a
Create Date: 2024-06-13 13:19:10.751344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d7359f1d51d'
down_revision = '54a43c606b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('realism', sa.String(length=64), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.drop_column('realism')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
