"""Adding gender & realism to Companions

Revision ID: 54a43c606b0a
Revises: 0db085bfa4f1
Create Date: 2024-06-13 13:10:03.866363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a43c606b0a'
down_revision = '0db085bfa4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('realism', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.drop_column('realism')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
