"""Trying again to add 2 new non-null cols

Revision ID: b02621fba538
Revises: 4d7359f1d51d
Create Date: 2024-06-13 13:20:55.096898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02621fba538'
down_revision = '4d7359f1d51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=64), server_default='Other', nullable=False))
        batch_op.add_column(sa.Column('realism', sa.String(length=64), server_default='Realistic', nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('companion', schema=None) as batch_op:
        batch_op.drop_column('realism')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
